---
- name: Create EC2 Instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        key_name: admin
        instance_type: t2.micro
        image_id: ami-0c7217cdde317cfec
        region: us-east-1    # Replace with your desired region
        count: 2
        vpc_subnet_id:  subnet-07733c29aea481570
        wait: yes
      register: ec2_instances


    - name: Get 
      debug: 
        var: ec2_instances.instances

    - name: Gather public IPs
      set_fact:
        public_ips: "{{ ec2_instances.instances | map(attribute='public_ip_address') | list }}"

    - name: Gather private IPs
      set_fact:
        private_ips : "{{ ec2_instances.instances | map(attribute='private_ip_address') | list }}"

    - name: Display public IPs
      debug:
        var: public_ips

    - name: Display private IPs
      debug:
        var: private_ips
    


    - name: Clean the inventory file
      replace:
        path: "{{ playbook_dir }}/inventory"
        regexp: '.*'  
        replace: ''   


    - name: Update inventory file
      blockinfile:
        path: "{{ playbook_dir }}/inventory"
        block: |
          all:
            hosts:
              host1:
                ansible_host: "{{ public_ips[0]  }}"
                mongo_name: master
                private_ip: "{{ private_ips[0] }}"
              host2:
                ansible_host: "{{ public_ips[1] }}"
                mongo_name: worker
                private_ip: "{{ private_ips[1] }}"

